# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder

# Set working directory
WORKDIR /app

# Install dependencies (skip prepare scripts)
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy source
COPY . .

# Build the project
RUN npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy production files from builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

# Set production environment
ENV NODE_ENV=production

# Expose nothing; uses stdio

# Default command
CMD ["node", "dist/index.js"]
